### ISSUE TITLE
No Such Key error

### ISSUE THREAD

**Issue by vincentcau** [k1LoW/serverless-s3-sync#69]
Hi i encounter this error on the sync.  And i discover that the probleme not arrived when i flush all assets in the s3. 

S3 Sync: Syncing directories and S3 prefixes...
............
S3 Sync: Synced.
S3 Sync: Syncing metadata...
 
  No Such Key --------------------------------------------
 
  NoSuchKey: The specified key does not exist.
      at Request.extractError (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/services/s3.js:816:35)
      at Request.callListeners (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
      at Request.emit (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
      at Request.emit (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:683:14)
      at Request.transition (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:22:10)
      at AcceptorStateMachine.runTo (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
      at /usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
      at Request.<anonymous> (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:38:9)
      at Request.<anonymous> (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:685:12)
      at Request.callListeners (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
      at Request.emit (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
      at Request.emit (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:683:14)
      at Request.transition (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:22:10)
      at AcceptorStateMachine.runTo (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
      at /usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
      at Request.<anonymous> (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:38:9)
      at Request.<anonymous> (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:685:12)
      at Request.callListeners (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
      at callNextListener (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
      at IncomingMessage.onEnd (/usr/lib/node_modules/serverless/node_modules/aws-sdk/lib/event_listeners.js:307:13)
      at IncomingMessage.emit (events.js:228:7)
      at IncomingMessage.EventEmitter.emit (domain.js:475:20)
      at endReadableNT (_stream_readable.js:1185:12)
      at processTicksAndRejections (internal/process/task_queues.js:81:21)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.15.0
     Framework Version:         1.67.0
     Plugin Version:            3.6.0
     SDK Version:               2.3.0
     Components Version:        2.22.3

**Comment by mmclafferty** [comment]
Experiencing the same issue here...

**Comment by vincentcau** [comment]
I think the problem is in the S3. For the moment the hack is to delete all the folders and files in the S3 :/ like `aws s3 rm s3://my_s3 --recursive`

**Comment by comandrei** [comment]
Still happens when syncing small directories and/or directories with . in their name

 Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              15.14.0
     Framework Version:         2.29.0 (local)
     Plugin Version:            4.5.3
     SDK Version:               n/a
     Components Version:        3.9.0
